# -*- coding: utf-8 -*-
"""lab.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YNzRj6KF2i6EDbFpC78Ql4Un0LkC4HDR
"""

!pip install biopython

from Bio import Align

human_hbb_rna = """ACATTTGCTTCTGACACAACTGTGTTCACTAGCAACCTCAAACAGACACCATGGTGCATCTGACTCCTGA
GGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAGTTGGTGGTGAGGCCCTGGGC
AGGCTGCTGGTGGTCTACCCTTGGACCCAGAGGTTCTTTGAGTCCTTTGGGGATCTGTCCACTCCTGATG
CTGTTATGGGCAACCCTAAGGTGAAGGCTCATGGCAAGAAAGTGCTCGGTGCCTTTAGTGATGGCCTGGC
TCACCTGGACAACCTCAAGGGCACCTTTGCCACACTGAGTGAGCTGCACTGTGACAAGCTGCACGTGGAT
CCTGAGAACTTCAGGCTCCTGGGCAACGTGCTGGTCTGTGTGCTGGCCCATCACTTTGGCAAAGAATTCA
CCCCACCAGTGCAGGCTGCCTATCAGAAAGTGGTGGCTGGTGTGGCTAATGCCCTGGCCCACAAGTATCA
CTAAGCTCGCTTTCTTGCTGTCCAATTTCTATTAAAGGTTCCTTTGTTCCCTAAGTCCAACTACTAAACT
GGGGGATATTATGAAGGGCCTTGAGCATCTGGATTCTGCCTAATAAAAAACATTTATTTTCATTGCAA""".replace('\n', '')
human_hbb_prot = """MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLG
AFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVAN
ALAHKYH""".replace('\n', '')
rat_hbb_rna = """TGCTTCTGACATAGTTGTGTTGACTCACAAACTCAGAAACAGACACCATGGTGCACCTGACTGATGCTGA
GAAGGCTGCTGTTAATGGCCTGTGGGGAAAGGTGAACCCTGATGATGTTGGTGGCGAGGCCCTGGGCAGG
CTGCTGGTTGTCTACCCTTGGACCCAGAGGTACTTTGATAGCTTTGGGGACCTGTCCTCTGCCTCTGCTA
TCATGGGTAACCCTAAGGTGAAGGCCCATGGCAAGAAGGTGATAAACGCCTTCAATGATGGCCTGAAACA
CTTGGACAACCTCAAGGGCACCTTTGCTCATCTGAGTGAACTCCACTGTGACAAGCTGCATGTGGATCCT
GAGAACTTCAGGCTCCTGGGCAATATGATTGTGATTGTGTTGGGCCACCACCTGGGCAAGGAATTCACCC
CCTGTGCACAGGCTGCCTTCCAGAAGGTGGTGGCTGGAGTGGCCAGTGCCCTGGCTCACAAGTACCACTA
AACCTCTTTTCCTGCTCTTGTCTTTGTGCAATGGTCAATTGTTCCCAAGAGAGCATCTGTCAGTTGTTGT
CAAAATGACAAAGACCTTTGAAAATCTGTCCTACTAATAAAAGGCATTTACTTTCACTGC""".replace('\n', '')
rat_hbb_prot = """MVHLTDAEKAAVNGLWGKVNPDDVGGEALGRLLVVYPWTQRYFDSFGDLSSASAIMGNPKVKAHGKKVIN
AFNDGLKHLDNLKGTFAHLSELHCDKLHVDPENFRLLGNMIVIVLGHHLGKEFTPCAQAAFQKVVAGVAS
ALAHKYH""".replace('\n', '')
human_ins_prot = """MALWMRLLPLLALLALWGPDPAAAFVNQHLCGSHLVEALYLVCGERGFFYTPKTRREAEDLQVGQVELGG
GPGAGSLQPLALEGSLQKRGIVEQCCTSICSLYQLENYCN""".replace('\n', '')

"""Task 1 is to align human and rat HBB RNA sequences.

1st case: match = 1; mismatch = 0; gap = 0.
"""

aligner = Align.PairwiseAligner()

aligner.match_score = 1
aligner.mismatch_score = 0
aligner.gap_score = 0
alignments11 = aligner.align(human_hbb_rna, rat_hbb_rna)
len(alignments11)

print(alignments11[0])
alignments11[0].substitutions

"""2nd case: match = 1; mismatch = -1; gap = -2."""

aligner.match_score = 1
aligner.mismatch_score = -1
aligner.gap_score = -2
alignments12 = aligner.align(human_hbb_rna, rat_hbb_rna)
len(alignments12)

print(alignments12[0])
alignments12[0].substitutions

"""3rd case: match = 1; mismatch = -2; gap = 0."""

aligner.match_score = 1
aligner.mismatch_score = -2
aligner.gap_score = 0
alignments13 = aligner.align(human_hbb_rna, rat_hbb_rna)
len(alignments13)

print(alignments13[0])
alignments13[0].substitutions

"""Task 2 is to align human and rat HBB protein sequences."""

blosum62 = Align.substitution_matrices.load("BLOSUM62")
aligner.substitution_matrix = blosum62

alignments21 = aligner.align(human_hbb_prot, rat_hbb_prot)
len(alignments)

print(alignments21[0])
matrix = alignments21[0].substitutions
matrix

from matplotlib import pyplot as plt
plt.imshow(matrix)
plt.colorbar()

"""Task 3 is to align human HBB and INS protein sequences."""

alignments31 = aligner.align(human_hbb_prot, human_ins_prot)
len(alignments31)

print(alignments31[0])
alignments31[0].substitutions

"""Additional task 4: to compare differences between protein sequences."""

matches1 = alignments21[0].counts().aligned
score1 = matches1 / len(human_hbb_prot)
print('human HBB vs rat HBB:', score1)

matches2 = alignments31[0].counts().aligned
score2 = matches2 / len(human_ins_prot)
print('human HBB vs rat HBB:', score2)

print ('human HBB is closer to rat HBB than to human INS:', score1 > score2)
